services:
    backend:
        build: ./backend
        image: ghcr.io/axenos-gr/wedding/backend:latest
        container_name: wedding-backend
        env_file: .env.backend
        ports:
            - "127.0.0.1:8080:8080"
        volumes:
            - ./uploads:/root/uploads
            - ./apk:/root/apk
        depends_on:
            postgres:
                condition: service_healthy
        restart: always
        environment:
            - TZ=Asia/Almaty
    frontend:
        build: ./frontend
        image: ghcr.io/axenos-gr/wedding/frontend:latest
        container_name: wedding-frontend
        ports:
            - "127.0.0.1:6001:6001"
        restart: always
        environment:
            - TZ=Asia/Almaty
    postgres:
        image: postgres:15-alpine
        container_name: wedding-db
        healthcheck:
            test:
                ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
            interval: 3s
            timeout: 3s
            retries: 5
            start_period: 2s
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "127.0.0.1:5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init-scripts:/docker-entrypoint-initdb.d
        restart: always

    pgadmin:
        image: dpage/pgadmin4
        container_name: wedding-pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        ports:
            - "127.0.0.1:5050:80"
        depends_on:
            - postgres
        restart: always

volumes:
    postgres_data:
