services:
    backend:
        image: ghcr.io/axenos-gr/wedding/backend:latest
        container_name: wedding-backend
        env_file: .env.backend
        ports:
            - "6000:6000"
        restart: on-failure:5
        environment:
            - TZ=Asia/Almaty
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
    postgres:
        image: postgres:15-alpine
        container_name: wedding-db
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init-scripts:/docker-entrypoint-initdb.d
        restart: always

    pgadmin:
        image: dpage/pgadmin4
        container_name: wedding-pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        ports:
            - "5050:80"
        depends_on:
            - postgres
        restart: always

volumes:
  postgres_data:
